/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    Button: typeof import('primevue/button')['default']
    Circ: typeof import('./src/components/SectionEditor/Circ.vue')['default']
    Circle: typeof import('./src/components/SectionEditor/Circle.vue')['default']
    Column: typeof import('primevue/column')['default']
    ConsoleLog: typeof import('./src/components/ConsoleLog.vue')['default']
    Copia: typeof import('./src/components/IfcLite - Copia.vue')['default']
    copy: typeof import('./src/components/Stream copy.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Ellipse: typeof import('./src/components/SectionEditor/Ellipse.vue')['default']
    Fiber: typeof import('./src/components/SectionEditor/Fiber.vue')['default']
    FibersCirc: typeof import('./src/components/SectionEditor/FibersCirc.vue')['default']
    FibersLine: typeof import('./src/components/SectionEditor/FibersLine.vue')['default']
    Fragments: typeof import('./src/components/Fragments.vue')['default']
    Gantt: typeof import('./src/components/Gantt.vue')['default']
    Handle: typeof import('./src/components/SectionEditor/Handle.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    IfcLite: typeof import('./src/components/IfcLite.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Line: typeof import('./src/components/SectionEditor/Line.vue')['default']
    Map: typeof import('./src/components/Ontario/Map.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Ontario: typeof import('./src/components/Ontario.vue')['default']
    OpenGeometryIo: typeof import('./src/components/OpenGeometryIo.vue')['default']
    Opera: typeof import('./src/components/Ontario/Opera.vue')['default']
    OpList: typeof import('./src/components/SectionEditor/OpList.vue')['default']
    Polygon: typeof import('./src/components/SectionEditor/Polygon.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    Quad: typeof import('./src/components/SectionEditor/Quad.vue')['default']
    Rect: typeof import('./src/components/SectionEditor/Rect.vue')['default']
    Reluis: typeof import('./src/components/Reluis.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    S2k: typeof import('./src/components/SectionEditor/S2k.vue')['default']
    Section: typeof import('./src/components/SectionEditor/Section.vue')['default']
    SectionEditor: typeof import('./src/components/SectionEditor.vue')['default']
    Select: typeof import('primevue/select')['default']
    SerpApi: typeof import('./src/components/SerpApi.vue')['default']
    Stirrup: typeof import('./src/components/SectionEditor/Stirrup.vue')['default']
    Stirrups: typeof import('./src/components/SectionEditor/Stirrups.vue')['default']
    Stream: typeof import('./src/components/Stream.vue')['default']
    Strip: typeof import('./src/components/SectionEditor/Strip.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    ThatOpen: typeof import('./src/components/ThatOpen.vue')['default']
    ThatOpen0: typeof import('./src/components/ThatOpen0.vue')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    Tri: typeof import('./src/components/Tri.vue')['default']
    TriFragments: typeof import('./src/components/TriFragments.vue')['default']
    TriViewer: typeof import('./src/components/TriViewer.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
