/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    ConsoleLog: typeof import('./src/components/ConsoleLog.vue')['default']
    Copia: typeof import('./src/components/Gantt - Copia.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Gantt: typeof import('./src/components/Gantt.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    OpenGeometryIo: typeof import('./src/components/OpenGeometryIo.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    Reluis: typeof import('./src/components/Reluis.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SerpApi: typeof import('./src/components/SerpApi.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tri: typeof import('./src/components/Tri.vue')['default']
    TriViewer: typeof import('./src/components/TriViewer.vue')['default']
  }
}
