name: get private file

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Scarica file dalla repository privata
        env:
          GITHUB_TOKEN: ${{ secrets.mylibs }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3.raw" \
              -o /libs/IO/index.ts
              https://api.github.com/repos/SpinoWeb/mylibs/contents/IO/index.ts
