steps:
  - name: Scarica file dalla repository privata
    env:
      GITHUB_TOKEN: ${{ secrets.mylibs }}
    run: |
      curl -H "Authorization: token $GITHUB_TOKEN" \
           -H "Accept: application/vnd.github.v3.raw" \
           -o /tmp/file_dalla_repo_privata \
           https://api.github.com/repos/SpinoWeb/mylibs/contents/IO/index.ts
